# Generated by Django 4.1.7 on 2023-02-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_short_ru',
            field=models.TextField(blank=True, max_length=2500, verbose_name='Описание короткое (рус.)'),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Проект'),
        ),
    ]
