# Generated by Django 4.1.7 on 2023-02-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
    ]
