# Generated by Django 4.1.7 on 2023-02-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_project_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ManyToManyField(blank=True, to='core.group', verbose_name='Группа'),
        ),
    ]
